Terraform scripts to deploy Author to ECS
ONSdigital/eq-author-deploy pull request #2
Opened 2017-09-28 13:53 UTC by jonnyshaw89

These Terraform scripts deploy Author to ECS

2017-09-28 14:03 UTC, samiwel approved these changes
Don't claim to understand this all yet, but seems to work 👍

2017-10-04 15:35 UTC, ajmaddaford requested changes

2017-10-04 15:35 UTC, ajmaddaford commented on author-api.tf
> +    DB_CONNECTION_URI  = "postgres://author:authorPassword@${aws_db_instance.author_database.address}:${aws_db_instance.author_database.port}/author"
The authorPassword bit probably needs looking at

2017-10-04 15:35 UTC, ajmaddaford commented on README.md
> +This repository hold the code that is responsible for deploying [Author](https://github.com/ONSdigital/eq-author) [Author API](https://github.com/ONSdigital/eq-author-api) and [Publisher](https://git
hold -> holds

2017-10-04 15:35 UTC, ajmaddaford commented on rds.tf
> +  password                    = "authorPassword"
This needs to be parameterised

2017-10-16 11:37 UTC, ajmaddaford approved these changes

2017-10-16 11:47 UTC, merged