Add Firebase authentication to author task definition
ONSdigital/eq-author-deploy pull request #7
Opened 2018-01-05 12:46 UTC by ajmaddaford

2018-01-05 16:14 UTC, ajmaddaford commented
![](https://github.trello.services/images/mini-trello-icon.png) [Integrate user sign in](https://trello.com/c/itrglzyg/296-integrate-user-sign-in)

2018-01-08 10:12 UTC, jonnyshaw89 commented on author.tf
> +    SKIP_AUTH           = "${var.skip_auth}"
Should we default this to false so we don't need to supply it?

2018-01-10 14:26 UTC, samiwel commented
Looks good to me. Where should the variables get set, would this happen in the Concourse pipeline?

2018-01-10 15:19 UTC, ajmaddaford commented
@samiwel For now staging will deploy as the developer Terraform does, without authentication. Jon is doing the work to integrate the smoke tests and as these haven't been updated to work with authentication they would fail. I've raised a pull request on https://github.com/ONSdigital/eq-deploy/pull/14 to add the firebase variables to the pre-prod deploy.

2018-01-10 15:21 UTC, jonnyshaw89 requested changes

2018-01-10 15:21 UTC, jonnyshaw89 commented on author.tf
> +    FIREBASE_MESSAGING_SENDER_ID = "${var.firebase_messaging_sender_id}"
You should fix the formatting here.

2018-01-10 16:40 UTC, jonnyshaw89 approved these changes

2018-01-11 14:48 UTC, MIslam92 approved these changes

2018-01-11 14:49 UTC, MIslam92 commented
@ajmaddaford "Squishy Squashy"

2018-01-11 15:02 UTC, merged